# Constants
ROW_COUNT = 6
COLUMN_COUNT = 7
TOKEN_RADIUS = 35
GAME_BOARD_WIDTH = 750
GAME_BOARD_HEIGHT = 600
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
# Colors
BACKGROUND_COLOR = "grey"
GAME_BOARD_COLOR = "darkblue"
RED_PLAYER_COLOR = "red"
YELLOW_PLAYER_COLOR = "yellow"
# location trackers
BOARD_OFFSET_X = 500
BOARD_OFFSET_Y = 250